[package]
name = "hash-wasm"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "1.0.219"
serde-wasm-bindgen = "0.6.5"
sha3 = "0.10.8"
wasm-bindgen = "0.2.100"
rayon = "1.10.0"

[lib]
crate-type = ["cdylib", "rlib"]
path = "lib.rs"
